jwt:
  header: Authorization
  secret: ${JWT_SECRET:jwt-secret}
  accessTokenLife: ${JWT_ACCESS_TOKEN_LIFE:604800}
  refreshTokenLife: ${JWT_REFRESH_TOKEN_LIFE:2592000}

initializer:
    enabled: ${INITIALIZER_ENABLED:true}
    username: ${INITIALIZER_USERNAME:admin@aupma.com}
    password: ${INITIALIZER_PASSWORD:admin}

totp:
  qrLabel: ${TOTP_QR_LABEL:AUPMA}
  issuer: ${TOTP_ISSUER:aupma.com}

spring:
  security:
    filter:
      order: 10
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mariadb://mariadb/spring-jwt-rest-starter}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:aupma}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
springdoc:
  pathsToMatch: /api/**

server:
  port: ${SERVER_PORT:8080}
